#!/bin/bash

kubectl label "$item"
$(kubectl get "$item" --output=json | jq -r -S '.metadata.labels | to_entries | .[] | select (.key | contains ("zone")) | "zone=\(.value)"' 2>/dev/null);

#random read + sequential write IOPS test
sudo fio -ioengine=psync -bs=32k -fdatasync=1 -thread -rw=randrw -percentage_random=100,0 -size=10G -filename=fio_randread_write_test.txt -name='fio mixed randread and sequential write test' -iodepth=4 -runtime=15 -numjobs=4 -group_reporting --output-format=json --output=fio_randread_write_test.json

#random read + sequential write Latency test:
sudo fio -ioengine=psync -bs=32k -fdatasync=1 -thread -rw=randrw -percentage_random=100,0 -size=10G -filename=fio_randread_write_latency_test.txt -name='fio mixed randread and sequential write test' -iodepth=1 -runtime=60 -numjobs=1 -group_reporting --output-format=json --output=fio_randread_write_latency_test.json

scp -i $PERM_PATH ~/pd-ctl ec2-user@$BASTION:/home/ec2-user

scp -i stg5tidb.pem ec2-user@10.223.65.7:/mnt/local-ssd/f7cd03b9-5a24-4416-8b73-56da42e52a6f/fio/*.json .

kubectl get TidbCluster stg1-tidb-cluster --namespace stg1 

#turns out pd-2, the leader is in 1a!

#verify context
kubectl get svc -n stg1

aws eks --region ap-northeast-1 update-kubeconfig --name stg5tidb

kubectl config current-context

kubectl get nodes --show-labels

kubectl get TidbCluster  -n tidb-admin

for item in $( kubectl get node --output=name);
  do kubectl label "$item" \
  $(kubectl get "$item" --output=json | jq -r -S '.metadata.labels | to_entries | .[] | select (.key | contains ("zone")) | "zone=\(.value)"' 2>/dev/null);
done

kubectl get po -n stg5tidb

kubectl get configmap -n stg5tidb

helm get values stg5tidb > ~/helm_stg5.yaml

kubectl describe configmap -n stg5tidb stg5tidb-tikv-c10d5a3e > ~/conf_tikv

kubectl describe configmap -n stg5tidb stg5tidb-tidb > ~/conf_tidb

kubectl logs stg5tidb-tidb-0 slowlog -n stg5tidb > ~/slow_q

kubectl logs stg5tidb-tidb-1 tidb -n stg5tidb > ~/log_tidb

kubectl exec -it stg5tidb-tidb-1 -n stg5tidb --container tidb  -- cat  /etc/tidb/tidb.toml


kubectl exec -it stg5tidb-tidb-1 -n stg5tidb --container tidb  -- ls /etc/tidb

kubectl logs stg5tidb-tidb-1 tidb -n stg5tidb > ~/log_tidb

kubectl describe configmap -n stg5tidb stg5tidb-tidb > ~/conf_tidb

kubectl logs stg5tidb-tikv-4 -n stg5tidb > ~/log_tikv


<<CON

You can grep loaded config: [INFO] [printer.go:54] ["loaded config"]

CON

kubectl port-forward -n stg5tidb svc/stg5tidb-pd 2379:2379

kubectl port-forward -n stg5tidb svc/stg5tidb-tidb-peer 10080:10080

go tool pprof http://localhost:10080/debug/pprof/heap

go tool pprof http://localhost:10080/debug/pprof/profile

kubectl port-forward -n stg5tidb svc/stg5tidb-pd 2379:2379

kubectl exec -it -n stg5tidb stg5tidb-tikv-1 -- du -sh /var/lib/tikv

