@startuml
[archiving data into tidb] --> [API to read archive db] 

[archiving data into tidb] --> [Clean up old data from Aurora] 

[API to read archive db] --> [Reduce the cut off period to 2 weeks] 

[Clean up old data from Aurora] --> [Reduce the cut off period to 2 weeks] 

[Reduce the cut off period to 2 weeks] --> [Wallet API test]

@enduml

@startuml
[Aurora hot] <-- [archiver]

[Aurora hot] <-- [Persist backup]

[archiver] --> [Cold db]

[purger] --> [refund & comp flow cold] 

[refund & comp flow cold] --> [Cold db]  

[Aurora hot] <-- [purger] 

[Aurora hot] <-- [binlog rep ignoring delete] 

[binlog rep ignoring delete] --> [replicated db]

@enduml

@startuml

[Payment] --> [Aurora Mar] 

[Payment] --> [Aurora Feb] 

[Refund db] --> [Aurora Jan]
[Refund db] --> [Aurora Feb]
[Refund db] --> [Aurora Mar]

[Refund] --> [Refund db]
@enduml




@startuml
[STG cluster] --> [STG new refund]
[STG cluster] --> [STG archiving immutable]
[STG new refund] --> [STG purge mutable]
[STG archiving immutable] --> [STG purge immutable]
[STG archiving immutable] --> [STG archiving mutable] 
[STG archiving immutable] --> [PROD cluster]
[Aurora persist] --> [PROD purge]
[PROD cluster] --> [PROD archive]
[PROD archive] --> [PROD purge]
[STG new refund] --> [PROD new refund]
[PROD new refund] --> [PROD purge]
[STG archiving mutable] --> [STG purge mutable]
[STG purge immutable] --> [STG purge mutable]
[STG purge mutable] --> [PROD purge]
@enduml




@startuml
skinparam component {
	backgroundColor<<done>> Green
	backgroundColor<<doing>> Yellow
	backgroundColor<<explore>> Blue
}

[Java] --> [Spring]
[Network] --> [RDS]
[Network] --> [Redis]
[RDS] --> [Spring]
[Java] --> [Kafka]
[Network] --> [Kafka]
@enduml
