#!/bin/bash
#set which profile to use
export AWS_PROFILE=user2

#describe instances
aws ec2 describe-instances --profile user2

#Delete streams from a specific month
export LOG_GROUP=dev_v2-cluster

aws logs describe-log-streams --log-group-name $LOG_GROUP --query 'logStreams[?starts_with(logStreamName,`2018/03`)].logStreamName' --output table | awk '{print $2}' | grep -v ^$ | while read x; do aws logs delete-log-stream --log-group-name $LOG_GROUP --log-stream-name $x; done

