#!bin/bash

terraform apply -var-file=multi.tfvars

CLUSTER_NAME=g2112
aws eks --region us-east-2 update-kubeconfig --name ${CLUSTER_NAME}

kubectl apply -f manifests/crd.yaml
kubectl apply -f manifests/local-volume-provisioner.yaml
kubectl apply -f manifests/gp2-storageclass.yaml
kubectl apply -f manifests/tiller-rbac.yaml
helm init --service-account tiller --upgrade --wait

###Is the cluster good now?
helm version

helm install charts/tidb-operator --name tidb-operator --namespace tidb-admin
<<OP

NOTES:
1. Make sure tidb-operator components are running
   kubectl get pods --namespace tidb-admin -l app.kubernetes.io/instance=tidb-operator
2. Install CRD
   kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
   kubectl get customresourcedefinitions
3. Modify tidb-cluster/values.yaml and create a TiDB cluster by installing tidb-cluster charts
   helm install tidb-cluster

OP

helm install charts/tidb-cluster --name dev1-tidb-cluster --namespace tidb --values dev1_tidb_cluster_values.yaml

helm install charts/tidb-cluster --name dev2-tidb-cluster --namespace dev2 --values dev2_tidb_cluster_values.yaml

<<DB

Cluster Startup
1. Watch tidb-cluster up and running
     watch kubectl get pods --namespace tidb -l app.kubernetes.io/instance=tidb-cluster-george -o wide
2. List services in the tidb-cluster
     kubectl get services --namespace tidb -l app.kubernetes.io/instance=tidb-cluster-george

Cluster access
* Access tidb-cluster using the MySQL client
    kubectl port-forward -n tidb svc/tidb-cluster-george-tidb 4000:4000 &
    mysql -h 127.0.0.1 -P 4000 -u root -D test
  Set a password for your user
    SET PASSWORD FOR 'root'@'%' = 'vW7fVonWrQ'; FLUSH PRIVILEGES;
* View monitor dashboard for TiDB cluster
   kubectl port-forward -n tidb svc/tidb-cluster-george-grafana 3000:3000
   Open browser at http://localhost:3000. The default username and password is admin/admin.
   If you are running this from a remote machine, you must specify the server's external IP address.

DB

kubectl get po -n tidb -lapp.kubernetes.io/component=tidb
