@startuml
!include <aws/common>
!include <aws/Compute/AmazonVPC/VPCpeering/VPCpeering>
!include <aws/NetworkingContentDelivery/AmazonRoute53/AmazonRoute53>
!include <aws/NetworkingContentDelivery/ElasticLoadBalancing/ElasticLoadBalancing>

package "Service vpc - Tokyo " {
[service k8s]
}
package "Tidb vpc - Tokyo "{
package "eks" {
[tidb-operator]
[tidb payment cluster]
[tidb BA cluster]
}
}

[service k8s] --> [tidb payment cluster] : VPC peering
[tidb payment cluster] --> [tidb BA cluster] : binlog replication
@enduml

VPCPEERING(peering)
peering --> "eks"

ELASTICLOADBALANCING(tidb_lb, LB provisioned by helm)
AMAZONROUTE53(tidb_dns, tidb dns name)
