#!/bin/bash

### Make sure you have NO OTHER mysql daemon running

cd tidb-docker-compose && docker-compose pull # Get the latest Docker images
docker-compose up -d

mysql -h 127.0.0.1 -P 4000 -u root



############
#Binary deployment
#start PD
./bin/pd-server --data-dir=pd \
	                --log-file=pd.log \
			-L=debug

#start TiKV
./bin/tikv-server --pd="127.0.0.1:2379" \
	                  --data-dir=tikv \
			                    --log-file=tikv.log \
			-L=debug
#start TiDB
./bin/tidb-server --store=tikv \
	                  --path="127.0.0.1:2379" \
			                    --log-file=tidb.log \
			-L=debug

#connect to TiDB
mysql -h 127.0.0.1 -P 4000 -u root -D test

nc -v 127.0.0.1 4000

######
#use dd to check disk performance
LANG='en_US.UTF-8' dd bs=4k count=250000 oflag=direct if=/dev/zero of=/home/ec2-user/deploy/io_test.txt 2>&1 | awk '/MB/{print $(NF-1)}'

lsblk
sudo dd if=/dev/xvda of=/dev/null bs=1M

dd bs=4k count=250000 conv=fsync if=/dev/zero of=/home/ec2-user/deploy/io_test.txt

LANG='en_US.UTF-8' dd bs=4k count=250000 oflag=direct if=/dev/zero of=/home/ec2-user/deploy/io_test.txt

