@startuml
skinparam component {
	backgroundColor<<done>> Green
	backgroundColor<<doing>> Yellow
	backgroundColor<<explore>> Blue
}

[STG consumer indexer recon]
note left: Aug 7
[STG traffic switch int test]
note left: Aug 13
[STG agg migration performance]
note left: Aug 8
[PERF consumer indexer perf]
note left: Aug 5 - 12
[PERF consumer indexer recon]
note left: Aug 12 - 14
[STG backup/restore drill]
note left: Aug 9
[STG DR Drill]
note left: Aug 12 - 14


[STG consumer indexer recon] --> [STG traffic switch int test] 
[STG agg migration performance] --> [STG traffic switch int test] 
[PERF consumer indexer perf] --> [PERF traffic switch int test] 
[PERF consumer indexer recon] --> [PERF traffic switch int test] 
[PERF agg migration performance] --> [PERF traffic switch int test] 
[PERF agg migration recon] --> [PERF traffic switch int test] 
[STG backup/restore drill] --> [PERF backup/restore drill]
[PERF backup/restore drill] --> [PERF DR drill]
[STG backup/restore drill] --> [STG DR drill]
[STG DR drill] --> [PERF DR drill]
[PERF traffic switch int test] --> [PERF scale up drill]
[STG traffic switch int test] --> [PERF traffic switch int test] 
[PERF traffic switch int test] --> [PERF payment read perf test]
[PERF DR drill] --> [PROD cluster provision] 
[PERF payment read perf test] --> [PROD cluster provision]
@enduml


