/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package ns;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class myrecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"myrecord\",\"namespace\":\"ns\",\"fields\":[{\"name\":\"f1\",\"type\":[\"long\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public Object f1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public myrecord() {}

  /**
   * All-args constructor.
   */
  public myrecord(Object f1) {
    this.f1 = f1;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return f1;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: f1 = (Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f1' field.
   */
  public Object getF1() {
    return f1;
  }

  /**
   * Sets the value of the 'f1' field.
   * @param value the value to set.
   */
  public void setF1(Object value) {
    this.f1 = value;
  }

  /** Creates a new myrecord RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new myrecord RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new myrecord RecordBuilder by copying an existing myrecord instance */
  public static Builder newBuilder(myrecord other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for myrecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<myrecord>
    implements org.apache.avro.data.RecordBuilder<myrecord> {

    private Object f1;

    /** Creates a new Builder */
    private Builder() {
      super(myrecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing myrecord instance */
    private Builder(myrecord other) {
            super(myrecord.SCHEMA$);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'f1' field */
    public Object getF1() {
      return f1;
    }
    
    /** Sets the value of the 'f1' field */
    public Builder setF1(Object value) {
      validate(fields()[0], value);
      this.f1 = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'f1' field has been set */
    public boolean hasF1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'f1' field */
    public Builder clearF1() {
      f1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public myrecord build() {
      try {
        myrecord record = new myrecord();
        record.f1 = fieldSetFlags()[0] ? this.f1 : (Object) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
