#!/bin/bash

###################

#Watch out for the correct kubectl context!
kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080

kubectl expose deployment hello-minikube --type=NodePort

#To access a service exposed via a node port, run this command in a shell after starting minikube to get the address:
curl $(minikube service hello-minikube --url)

#To access the Kubernetes Dashboard, run this command in a shell after starting minikube to get the address:
minikube dashboard

kubectl apply -f https://k8s.io/examples/application/deployment.yaml

kubectl describe deployment nginx-deployment

#List the pods created by the deployment. For similar purposes, can use --show-labels instead of -l
kubectl get pods -l app=nginx

kubectl describe pod <pod-name>

#####clean up########
kubectl delete services hello-minikube

kubectl delete deployment hello-minikube

#shuts down the minikube virtual machine, but preserves all cluster state and data. Starting the cluster again will restore it to it’s previous state.
minikube stop


