#!/bin/bash

### see what is released
helm ls

### You get a simple idea of the features of this MySQL chart by running 
helm inspect stable/mysql

## To see what options are configurable on a chart, use 
helm inspect values stable/mariadb

### override any of these settings, use -f or --values options
cat << EOF > config.yaml
mariadbUser: user0
mariadbDatabase: user0db
EOF
helm install -f config.yaml stable/mariadb

### When it is time to uninstall or delete a release from the cluster, use the helm delete command
helm delete happy-panda

helm create deis-workflow
#### Now there is a chart in ./deis-workflow. You can edit it and create your own templates

### As you edit your chart, you can validate that it is well-formatted by running 
helm lint
### When it’s time to package the chart up for distribution
### Once you have edited a chart, helm can package it into a chart archive for you:
helm package deis-workflow

### List the deployed packages with their release versions by running
helm ls --deleted


