#!/bin/bash

#show which processes are using a specified file, file system, or unix socket.
fuser -m -u /mnt/usb1

#check what processes are using a network port
fuser -v -n tcp 80

#view the port associated with a daemon
lsof -i -n -P | grep sendmail

#io writes - maybe use dstat?
iostat

#check memory, unit kb, buffter is buffer cache in memory, 
#second line is the memory used by the program = free + buffers + cached. Note that buffers and cached are considered used from OS pov
#grep oom_killer is /var/log/messages
free

top -p pid_value

top -u franshesco

#sort by %CPU
top -o %CPU

pmap -x [pid]

#starts the program abcd in the background in such a way that the subsequent logout does not stop it.
#nohup is often used in combination with the nice command to run processes on a lower priority
nohup abcd &

#check context switch times, 10 times, once per second, see if cs >> in. Can use pidstat on top of it
vmstat -1 -10

# Set the maximum number of open files to 10.
ulimit -n 10

#d, l, s(ocket), c(har device), p(ipe), -(other, e.g., normal file)
#add exec permission
chmod u+x xxx.sh

#make the file readonly by the group and other user
chmod go-w xxx.sh

