#!/bin/bash

<<LINK
& run multiple commands in the background
&& run the next one only if the first one returns 0
|| run the second one if the frist one returns non-0

$($IF) && $($THEN) || $(ELSE)

LINK


#delete the folder if it exists, note that the spaces around -d predicate matter! 
[ -d $FOLDER ] && rm -r $FOLDER

#But -d does not work with wildcards! 0 - stdin 1 - stdout 2 - stderr &1 means it is not a file but a file descriptor
# note the positiovne of 2>&1 matters, have to go AFTER the file, otherwise &1 means the current console - bash loads from left to right!
if ls /path/to/your/files* 1> /dev/null 2>&1; then
      echo "files do exist"

#compress and decompress, -c compress, -x extract
tar -czvf $TO.tar.gz $FROM

#display error code of the last command,e.g., use it after a semicolon 
echo $?
#similarly, !$ is the last argument of the previous command
cd !$

#use of CDPATH, probably what to edit your ~/.bashrc

#automatically corrects small typos in directory names and jumps to the best guess of existing directories.
shopt -s cdspell

#shell to exit if any subcommand or pipeline returns a non-zero status
set -e

#multiline to a single line
cat file.txt|xargs

#single to multilines
cat single.txt | xargs -n 3
#replace tab with space
tr '\t' ' '

#delete all digits
tr -d '0-9'

#remove duplicate spaces
cat file | tr -s ' '

#cut 2nd and 4th column
cut -f2,4 file

#get all but 3rd column
cut -f3 --complement file

#search only files with certain extensions
grep -r --include=*.scala 'spray' ./ | less

#record terminal output
script my.terminal.seeesion

#creating a new environment without any existing environment variables for a new shell
env -i /bin/sh

#Note that this use of env is often unnecessary since most shells support setting environment variables in front of a command
env DISPLAY=foo.bar:1.0 xcalc

#take out --decode to encode
base64 --decode ${FILE_PATH}

# -n to not append the extra newline, use --decode after base64 to decode
echo -n ${DD_KEY} | base64 

#It’s similar to $() in that the output of the command inside is re-used. In this case, though, the output is treated as a file. This file can be used as an argument to commands that take files as an argument.
diff <(grep somestring file1) <(grep somestring file2)

#!$ repeats the last argument of the last command

#!:1-$ It takes all the arguments to the previous command and drops them in.

#default value for variables
#You can also assign directly with ${VAR:=defaultval} (equals sign, not dash) but note that this won’t work with positional variables in scripts or functions.
THIRD_ARG="${3:-no_third_arg}"


#show which processes are using a specified file, file system, or unix socket.
fuser -m -u /mnt/usb1

#check what processes are using a network port
fuser -v -n tcp 80

pmap -x [pid]

#starts the program abcd in the background in such a way that the subsequent logout does not stop it.
#nohup is often used in combination with the nice command to run processes on a lower priority
nohup abcd &

# Set the maximum number of open files to 10.
ulimit -n 10

#d, l, s(ocket), c(har device), p(ipe), -(other, e.g., normal file)
#add exec permission
chmod u+x xxx.sh

#make the file readonly by the group and other user
chmod go-w xxx.sh

###screen
#start a new screen session with session name
screen -S sessionName
screen -d -R sessionName

#list running sessions/screens	
screen -ls

#back to the same terminal
screen -r
