#!/bin/bash

#show which processes are using a specified file, file system, or unix socket.
fuser -m -u /mnt/usb1

#check what processes are using a network port
fuser -v -n tcp 80

#view the port associated with a daemon
lsof -i -n -P | grep sendmail

#io writes - maybe use dstat?
iostat

#current port usage
netstat -an

#check memory, unit kb, buffter is buffer cache in memory, 
free

top -p pid_value

top -u franshesco

#sort by %CPU
top -o %CPU

pmap -x [pid]

