#!/bin/bash

####Pod######
kubectl get pod

#List the pods created by the deployment. For similar purposes, can use --show-labels instead of -l
kubectl get pods -l app=nginx

kubectl describe pod $POD_NAME

####Deployment#####
kubectl get deployments

kubectl describe deployment nginx-deployment

####Services#####

kubectl get services

kubectl describe service mockservice
