#!/bin/bash

kops export kubecfg --name $CLUSTER_ADDR --state s3://$S3_BUCKET

####Pod######
kubectl get pod

#List the pods created by the deployment. For similar purposes, can use --show-labels instead of -l
kubectl get pods -l app=nginx

kubectl describe pod $POD_NAME

####Deployment#####
kubectl get deployments

kubectl describe deployment nginx-deployment

####Services#####

kubectl get services

kubectl describe service mockservice

#populate env var to the first column of the 2nd line
export POD_NAME=$(kubectl get pods -l k8s-app=mockservice | sed -n 2p | awk '{ print $1 }')
